name: work_done
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  intl: ^0.19.0
  sqflite: ^2.3.2
  path: ^1.8.3
  flutter_slidable: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets :
  - assets/Images/Mobile.png
  - assets/Images/check-square.png
  - assets/Images/checklist.png
  - assets/Images/image.png
  - assets/Images/reminders.png
  - assets/Images/task-searching.png
  - assets/Images/direction.png
